language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - SYMFONY_ENV=dev
  - SYMFONY_ENV=prod


matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install --require-dev

script:
  - phpunit --coverage-text
  - phpcs /src

# omitting "script:" will default to phpunit
# use the $SYMFONY_ENV env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$SYMFONY_ENV.xml --coverage-text
